// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


// import HelloController from "./hello_controller.js"
// application.register("hello", HelloController)

import InsertFromApiController from "./insert_from_api_controller.js"
application.register("insert-from-api", InsertFromApiController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller.js"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CheckboxBookingsController from "./checkbox_bookings_controller.js"
application.register("checkbox-bookings", CheckboxBookingsController)
